name: dicta_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  bloc: ^8.1.2
  card_swiper: ^3.0.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_switch: ^0.3.2
  go_router: ^11.1.1
  google_fonts: ^6.1.0
  mocktail: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Gotham-Light
      fonts:
        - asset: assets/fonts/Gotham-Light.otf

    - family: Gotham-Black
      fonts:
        - asset: assets/fonts/Gotham-Black.otf

    - family: Gotham-Medium
      fonts:
        - asset: assets/fonts/Gotham-Medium.otf

    - family: Gotham-Book
      fonts:
        - asset: assets/fonts/Gotham-Book.otf

    - family: Gotham-Bold
      fonts:
        - asset: assets/fonts/Gotham-Bold.otf
